/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DhirajDhotreRouteImport } from './routes/dhiraj-dhotre'
import { Route as JoinRouteImport } from './routes/join'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PersonProfileRouteImport } from './routes/person-profile'
import { Route as NewsPublicationsRouteImport } from './routes/news-publications'
import { Route as NewsCareerNotificationsRouteImport } from './routes/news-career-notifications'
import { Route as NewsAnnouncementsRouteImport } from './routes/news-announcements'
import { Route as NewsMediaRouteImport } from './routes/news-media'
import { Route as NewsTalksRouteImport } from './routes/news-talks'
import { Route as ResearchFacilitiesRouteImport } from './routes/research-facilities'
import { Route as ResearchDomainsRouteImport } from './routes/research-domains'
import { Route as ResearchTrackRouteImport } from './routes/research-track'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DhirajDhotreRoute = DhirajDhotreRouteImport.update({
  id: '/dhiraj-dhotre',
  path: '/dhiraj-dhotre',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonProfileRoute = PersonProfileRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsPublicationsRoute = NewsPublicationsRouteImport.update({
  id: '/news/publications',
  path: '/news/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsCareerNotificationsRoute = NewsCareerNotificationsRouteImport.update({
  id: '/news/career-notifications',
  path: '/news/career-notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsAnnouncementsRoute = NewsAnnouncementsRouteImport.update({
  id: '/news/announcements',
  path: '/news/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsMediaRoute = NewsMediaRouteImport.update({
  id: '/news/media',
  path: '/news/media',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsTalksRoute = NewsTalksRouteImport.update({
  id: '/news/talks',
  path: '/news/talks',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchFacilitiesRoute = ResearchFacilitiesRouteImport.update({
  id: '/research/facilities',
  path: '/research/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchDomainsRoute = ResearchDomainsRouteImport.update({
  id: '/research/domains',
  path: '/research/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchTrackRoute = ResearchTrackRouteImport.update({
  id: '/research/$trackSlug',
  path: '/research/$trackSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dhiraj-dhotre': typeof DhirajDhotreRoute
  '/join': typeof JoinRoute
  '/news': typeof NewsRoute
  '/people': typeof PeopleRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/people/$personId': typeof PersonProfileRoute
  '/news/announcements': typeof NewsAnnouncementsRoute
  '/news/career-notifications': typeof NewsCareerNotificationsRoute
  '/news/media': typeof NewsMediaRoute
  '/news/publications': typeof NewsPublicationsRoute
  '/news/talks': typeof NewsTalksRoute
  '/research/domains': typeof ResearchDomainsRoute
  '/research/facilities': typeof ResearchFacilitiesRoute
  '/research/$trackSlug': typeof ResearchTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dhiraj-dhotre': typeof DhirajDhotreRoute
  '/join': typeof JoinRoute
  '/news': typeof NewsRoute
  '/people': typeof PeopleRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/people/$personId': typeof PersonProfileRoute
  '/news/announcements': typeof NewsAnnouncementsRoute
  '/news/career-notifications': typeof NewsCareerNotificationsRoute
  '/news/media': typeof NewsMediaRoute
  '/news/publications': typeof NewsPublicationsRoute
  '/news/talks': typeof NewsTalksRoute
  '/research/domains': typeof ResearchDomainsRoute
  '/research/facilities': typeof ResearchFacilitiesRoute
  '/research/$trackSlug': typeof ResearchTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dhiraj-dhotre': typeof DhirajDhotreRoute
  '/join': typeof JoinRoute
  '/news': typeof NewsRoute
  '/people': typeof PeopleRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/people/$personId': typeof PersonProfileRoute
  '/news/announcements': typeof NewsAnnouncementsRoute
  '/news/career-notifications': typeof NewsCareerNotificationsRoute
  '/news/media': typeof NewsMediaRoute
  '/news/publications': typeof NewsPublicationsRoute
  '/news/talks': typeof NewsTalksRoute
  '/research/domains': typeof ResearchDomainsRoute
  '/research/facilities': typeof ResearchFacilitiesRoute
  '/research/$trackSlug': typeof ResearchTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dhiraj-dhotre'
    | '/join'
    | '/news'
    | '/people'
    | '/publications'
    | '/research'
    | '/people/$personId'
    | '/news/announcements'
    | '/news/career-notifications'
    | '/news/media'
    | '/news/publications'
    | '/news/talks'
    | '/research/domains'
    | '/research/facilities'
    | '/research/$trackSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dhiraj-dhotre'
    | '/join'
    | '/news'
    | '/people'
    | '/publications'
    | '/research'
    | '/people/$personId'
    | '/news/announcements'
    | '/news/career-notifications'
    | '/news/media'
    | '/news/publications'
    | '/news/talks'
    | '/research/domains'
    | '/research/facilities'
    | '/research/$trackSlug'
  id:
    | '__root__'
    | '/'
    | '/dhiraj-dhotre'
    | '/join'
    | '/news'
    | '/people'
    | '/publications'
    | '/research'
    | '/people/$personId'
    | '/news/announcements'
    | '/news/career-notifications'
    | '/news/media'
    | '/news/publications'
    | '/news/talks'
    | '/research/domains'
    | '/research/facilities'
    | '/research/$trackSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DhirajDhotreRoute: typeof DhirajDhotreRoute
  JoinRoute: typeof JoinRoute
  NewsRoute: typeof NewsRoute
  PeopleRoute: typeof PeopleRoute
  PublicationsRoute: typeof PublicationsRoute
  ResearchRoute: typeof ResearchRoute
  PersonProfileRoute: typeof PersonProfileRoute
  NewsAnnouncementsRoute: typeof NewsAnnouncementsRoute
  NewsCareerNotificationsRoute: typeof NewsCareerNotificationsRoute
  NewsMediaRoute: typeof NewsMediaRoute
  NewsPublicationsRoute: typeof NewsPublicationsRoute
  NewsTalksRoute: typeof NewsTalksRoute
  ResearchFacilitiesRoute: typeof ResearchFacilitiesRoute
  ResearchDomainsRoute: typeof ResearchDomainsRoute
  ResearchTrackRoute: typeof ResearchTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dhiraj-dhotre': {
      id: '/dhiraj-dhotre'
      path: '/dhiraj-dhotre'
      fullPath: '/dhiraj-dhotre'
      preLoaderRoute: typeof DhirajDhotreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PersonProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/announcements': {
      id: '/news/announcements'
      path: '/news/announcements'
      fullPath: '/news/announcements'
      preLoaderRoute: typeof NewsAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/career-notifications': {
      id: '/news/career-notifications'
      path: '/news/career-notifications'
      fullPath: '/news/career-notifications'
      preLoaderRoute: typeof NewsCareerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/media': {
      id: '/news/media'
      path: '/news/media'
      fullPath: '/news/media'
      preLoaderRoute: typeof NewsMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/publications': {
      id: '/news/publications'
      path: '/news/publications'
      fullPath: '/news/publications'
      preLoaderRoute: typeof NewsPublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/talks': {
      id: '/news/talks'
      path: '/news/talks'
      fullPath: '/news/talks'
      preLoaderRoute: typeof NewsTalksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/domains': {
      id: '/research/domains'
      path: '/research/domains'
      fullPath: '/research/domains'
      preLoaderRoute: typeof ResearchDomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/facilities': {
      id: '/research/facilities'
      path: '/research/facilities'
      fullPath: '/research/facilities'
      preLoaderRoute: typeof ResearchFacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$trackSlug': {
      id: '/research/$trackSlug'
      path: '/research/$trackSlug'
      fullPath: '/research/$trackSlug'
      preLoaderRoute: typeof ResearchTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DhirajDhotreRoute: DhirajDhotreRoute,
  JoinRoute: JoinRoute,
  NewsRoute: NewsRoute,
  PeopleRoute: PeopleRoute,
  PublicationsRoute: PublicationsRoute,
  ResearchRoute: ResearchRoute,
  PersonProfileRoute: PersonProfileRoute,
  NewsAnnouncementsRoute: NewsAnnouncementsRoute,
  NewsCareerNotificationsRoute: NewsCareerNotificationsRoute,
  NewsMediaRoute: NewsMediaRoute,
  NewsPublicationsRoute: NewsPublicationsRoute,
  NewsTalksRoute: NewsTalksRoute,
  ResearchFacilitiesRoute: ResearchFacilitiesRoute,
  ResearchDomainsRoute: ResearchDomainsRoute,
  ResearchTrackRoute: ResearchTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
